version: '2'

tasks:
  dev:
    cmds:
      - telepresence --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code node:12 /bin/bash

  build:
    cmds:
      - docker build -t evertras/events-demo-client .

  install-local:
    cmds:
      - kubectl apply -f deploy/k8s/all.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/k8s/all.yaml

