version: '2'

tasks:
  inject:
    cmds:
      - telepresence --swap-deployment events-demo-client --expose 80 --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code node:12 npx ng serve --port 80 --host 0.0.0.0 --disableHostCheck true

  build:
    cmds:
      - docker build -t evertras/events-demo-client .

  install-local:
    cmds:
      - kubectl apply -f deploy/k8s/all.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/k8s/all.yaml

