// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     inviteSent.avsc
 *     userRegistered.avsc
 */

package friendevents

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type InviteSent struct {
	FromID     string
	ToID       string
	TimeUnixMs int64
	ToEmail    string
}

func NewInviteSentWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &InviteSent{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeInviteSent(r io.Reader) (*InviteSent, error) {
	t := NewInviteSent()
	err := deserializeField(r, t.Schema(), t.Schema(), t)
	return t, err
}

func DeserializeInviteSentFromSchema(r io.Reader, schema string) (*InviteSent, error) {
	t := NewInviteSent()
	err := deserializeField(r, schema, t.Schema(), t)
	return t, err
}

func NewInviteSent() *InviteSent {
	return &InviteSent{}
}

func (r *InviteSent) Schema() string {
	return "{\"fields\":[{\"name\":\"FromID\",\"type\":\"string\"},{\"name\":\"ToID\",\"type\":\"string\"},{\"logicalType\":\"timestamp-millis\",\"name\":\"TimeUnixMs\",\"type\":\"long\"},{\"name\":\"ToEmail\",\"type\":\"string\"}],\"name\":\"InviteSent\",\"namespace\":\"com.evertras.events-demo.events\",\"type\":\"record\",\"version\":\"1\"}"
}

func (r *InviteSent) SchemaName() string {
	return "com.evertras.events-demo.events.InviteSent"
}

func (r *InviteSent) Serialize(w io.Writer) error {
	return writeInviteSent(r, w)
}

func (_ *InviteSent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *InviteSent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *InviteSent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *InviteSent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *InviteSent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *InviteSent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *InviteSent) SetString(v string)   { panic("Unsupported operation") }
func (_ *InviteSent) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *InviteSent) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.FromID)
	case 1:
		return (*types.String)(&r.ToID)
	case 2:
		return (*types.Long)(&r.TimeUnixMs)
	case 3:
		return (*types.String)(&r.ToEmail)

	}
	panic("Unknown field index")
}
func (r *InviteSent) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *InviteSent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *InviteSent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *InviteSent) Finalize()                        {}

type InviteSentReader struct {
	r io.Reader
	p *vm.Program
}

func NewInviteSentReader(r io.Reader) (*InviteSentReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewInviteSent()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &InviteSentReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *InviteSentReader) Read() (*InviteSent, error) {
	t := NewInviteSent()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
