FROM golang:1.13-alpine AS go-builder

WORKDIR /go/src/github.com/Evertras/events-demo
COPY . .
ARG BUILD_TAGS

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
      go build -a -tags "netgo ${BUILD_TAGS}" \
        -ldflags '-w -extldflags "-static"' \
        -o /processor \
        ./cmd/processor/main.go

FROM scratch

COPY --from=go-builder /processor processor

ENTRYPOINT ["/processor"]

