version: '2'

tasks:
  dev:
    cmds:
      - telepresence --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code golang:1.13 /bin/bash

  build:
    cmds:
      - docker build -t evertras/events-demo-auth .

  install-local:
    cmds:
      - kubectl apply -f deploy/all.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/all.yaml

