version: '2'

tasks:
  dev:
    cmds:
      - telepresence --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code golang:1.13 /bin/bash

  build:
    cmds:
      - go build -v cmd/ingest/main.go

