version: '2'

tasks:
  avro:
    sources:
      - schemas/avro/*.avsc
    generates:
      - lib/stream/authevents/*.go
    cmds:
      - mkdir -p lib/stream/authevents/
      - gogen-avro --package authevents lib/stream/authevents/ ./schemas/avro/*.avsc

  dev:
    cmds:
      - telepresence --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code golang:1.13 /bin/bash

  inject:
    cmds:
      - telepresence --swap-deployment auth-api --expose 13041 --docker-run --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code golang:1.13 /bin/bash

  build:
    deps:
      - avro
    cmds:
      - docker build -t evertras/events-demo-auth .

  build-redis:
    dir: deploy/redis
    cmds:
      - docker build -t evertras/events-demo-auth-redis .

  test:
    deps:
      - avro
    cmds:
      - go test -v ./lib/...

  install-local:
    deps:
      - build
      - build-redis
    cmds:
      - kubectl apply -f deploy/main.yaml
      - kubectl apply -f deploy/redis-commander.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/main.yaml
      - kubectl delete -f deploy/redis-commander.yaml

  update-local:
    deps:
      - build
    cmds:
      - kubectl scale deployment.v1.apps/auth-api --replicas=0
      - kubectl scale deployment.v1.apps/auth-api --replicas=2

