---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
  namespace: events-demo
spec:
  selector:
    app: jaeger
  clusterIP: None
  ports:
    - name: zipkin-legacy
      protocol: UDP
      port: 5775
    - name: jaeger-thrift-compact
      protocol: UDP
      port: 6831
    - name: jaeger-thrift-binary
      protocol: UDP
      port: 6832
    - name: agent-configs
      protocol: TCP
      port: 5778
    - name: front
      protocol: TCP
      port: 16686
    - name: jaeger-thrift-direct
      protocol: TCP
      port: 14268
    - name: zipkin-endpoint
      protocol: TCP
      port: 9411
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger
  namespace: events-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.7
        imagePullPolicy: IfNotPresent
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: jaeger.localhost
    http:
      paths:
        - path: /
          backend:
            serviceName: jaeger
            servicePort: front

