version: '2'

tasks:
  inject:
    cmds:
      - telepresence --swap-deployment presence --expose 13337 --docker-run -e JAEGER_AGENT_HOST=jaeger -e JAEGER_SAMPLER_TYPE=const -e JAEGER_SAMPLER_PARAM=1 --rm -it -v ${PWD}:/usr/local/code -w /usr/local/code golang:1.13 /bin/bash
  build:
    cmds:
      - docker build -t evertras/events-demo-presence .

  install-local:
    deps:
      - build
    cmds:
      - kubectl apply -f deploy/all.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/all.yaml

