FROM golang:1.13

RUN apt-get update
RUN apt-get install libssl-dev pkg-config
RUN curl -Lo /tmp/seabolt.tar.gz https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-18.04.tar.gz
RUN tar zxvf /tmp/seabolt.tar.gz --strip-components=1 -C /

WORKDIR /go/src/github.com/Evertras/events-demo

