version: '2'

tasks:
  dev:
    cmds:
      - docker build -f Dockerfile.dev -t events-demo-friends-dev .
      - telepresence --docker-run --rm -it -e JAEGER_AGENT_HOST=jaeger -e JAEGER_SAMPLER_TYPE=const -e JAEGER_SAMPLER_PARAM=1 -v ${PWD}:/go/src/github.com/Evertras/events-demo events-demo-friends-dev /bin/bash

  build:
    cmds:
      - docker build -t evertras/events-demo-friends .

  install-local:
    deps:
      - build
    cmds:
      - kubectl apply -f deploy/all.yaml

  delete-local:
    cmds:
      - kubectl delete -f deploy/all.yaml

