---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: events-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: evertras/events-demo-client:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: events-demo
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: client
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-ingress
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: events-demo.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: http

