---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: events-demo-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-demo-auth
  template:
    metadata:
      labels:
        app: events-demo-auth
    spec:
      containers:
      - name: events-demo-auth-container
        image: evertras/events-demo-auth:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: events-demo-auth-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: events-demo.localhost
    http:
      paths:
      - path: /api/auth
        backend:
          serviceName: events-demo-auth-service
          servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: events-demo-auth-service
spec:
  ports:
  - name: http
    targetPort: 13041
    port: 13041
  selector:
    app: events-demo-auth

