---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-processor
  namespace: events-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-processor
  template:
    metadata:
      labels:
        app: auth-processor
    spec:
      containers:
      - name: auth
        image: evertras/events-demo-auth-processor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-api
  namespace: events-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth
        image: evertras/events-demo-auth-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: events-demo
spec:
  ports:
  - name: http
    targetPort: 13041
    port: 13041
  selector:
    app: auth-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: events-demo.localhost
    http:
      paths:
      - path: /api/auth
        backend:
          serviceName: auth-api
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress-admin
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: admin.localhost
    http:
      paths:
      - path: /api/auth
        backend:
          serviceName: auth-api
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-db
  namespace: events-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db
        image: evertras/events-demo-auth-redis:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: events-demo
spec:
  ports:
  - name: db
    targetPort: 6379
    port: 6379
  selector:
    app: auth-db
