---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: profile
  namespace: events-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile-container
        image: evertras/events-demo-profile:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: events-demo
spec:
  ports:
  - name: http
    targetPort: 13083
    port: 13083
  selector:
    app: profile
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: profile-ingress
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://auth-api:13041/check
    ingress.kubernetes.io/auth-response-headers: X-User-ID
spec:
  rules:
  - host: events-demo.localhost
    http:
      paths:
      - path: /api/profile
        backend:
          serviceName: profile
          servicePort: http

