---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: friends-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: friends-processor
  template:
    metadata:
      labels:
        app: friends-processor
    spec:
      containers:
      - name: friends
        image: evertras/events-demo-friends-processor:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: friends-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: friends-api
  template:
    metadata:
      labels:
        app: friends-api
    spec:
      containers:
      - name: friends-api
        image: evertras/events-demo-friends-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: JAEGER_AGENT_HOST
          value: jaeger
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: friends-api
spec:
  ports:
  - name: http
    targetPort: 13030
    port: 13030
  selector:
    app: friends-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: friends-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friends-db
  template:
    metadata:
      labels:
        app: friends-db
    spec:
      containers:
      - name: db
        image: neo4j:3.5.12
        imagePullPolicy: IfNotPresent
        env:
        - name: NEO4J_AUTH
          value: none

        - name: NEO4J_dbms_connectors_default__listen__address
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: friends-db
spec:
  ports:
  - name: http
    targetPort: 7474
    port: 7474
  - name: bolt
    targetPort: 7687
    port: 7687
  selector:
    app: friends-db
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: friends
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: forward
    ingress.kubernetes.io/auth-url: http://auth-api:13041/check
    ingress.kubernetes.io/auth-response-headers: X-User-ID
spec:
  rules:
  - host: events-demo.localhost
    http:
      paths:
      - path: /api/friends
        backend:
          serviceName: friends
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: friends-db-ui
  namespace: events-demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: friends-db.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: friends-db
          servicePort: http

